language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install flake8 codecov
services:
  - postgresql
before_script:
  - psql -c 'create database bootcamp;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - coverage run manage.py test
  - flake8 --count --show-source --exclude=migrations
after_success:
  - codecov
deploy:
  provider: heroku
  buildpack: python
  app: web-bootcamp
  api_key:
    secure: "a3aa6d37-4504-4dc1-b1ce-6c58ac64ba21"
  run:
    - "python manage.py makemigrations && python manage.py migrate"
