language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install flake8
services:
  - postgresql
before_script:
  - psql -c 'create database bootcamp;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - flake8 bootcamp/ manage.py
  - python manage.py test
deploy:
  provider: heroku
  buildpack: python
  app: web-bootcamp
  api_key:
    secure: "a3aa6d37-4504-4dc1-b1ce-6c58ac64ba21"
  run:
    - "python manage.py makemigrations && python manage.py migrate"
